# Generated by Django 5.2.4 on 2025-07-31 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('vender', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='vendors.vendors')),
            ],
        ),
    ]
